export const ACTION_TYPES = {
  GET_PIZZAS_REQUEST: "GET_PIZZAS_REQUEST",
  GET_PIZZAS_SUCCESS: "GET_PIZZAS_SUCCESS",
  GET_PIZZAS_ERROR: "GET_PIZZAS_ERROR",
  GET_PIZZA_REQUEST: "GET_PIZZA_REQUEST",
  GET_PIZZA_SUCCESS: "GET_PIZZA_SUCCESS",
  GET_PIZZA_ERROR: "GET_PIZZA_ERROR",
  DELETE_PIZZA_REQUEST: "DELETE_PIZZA_REQUEST",
  DELETE_PIZZA_SUCCESS: "DELETE_PIZZA_SUCCESS",
};
